version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"

  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: etcd-server
    command: >
      /usr/local/bin/etcd
      --name etcd-node
      --advertise-client-urls http://etcd:2379
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd:2380
      --initial-cluster etcd-node=http://etcd:2380
      --initial-cluster-token etcd-cluster-token
      --initial-cluster-state new
    ports:
      - "2379:2379"
      - "2380:2380"
