version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: scoreboard
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - scoreboard_net

  redis:
    image: redis:latest
    container_name: redis_cache
    volumes:
      - redis_data:/data
    networks:
      - scoreboard_net

  gaming_service:
    build: ./gaming_service
    container_name: gaming_service
    environment:
      - DB_HOST=mysql_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=scoreboard
      - REDIS_HOST=redis_cache
    networks:
      - scoreboard_net
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Ensure this path is correct and the file exists
    ports:
      - "80:80"
    networks:
      - scoreboard_net
    depends_on:
      - gaming_service

volumes:
  mysql_data:
  redis_data:

networks:
  scoreboard_net:
