version: '3.7'

services:
  python-app1:
    build:
      context: .
      dockerfile: Dockerfile.app1
    volumes:
      - logs:/var/log

  python-app2:
    build:
      context: .
      dockerfile: Dockerfile.app2
    volumes:
      - logs:/var/log

  fluent-bit:
    image: fluent/fluent-bit:latest
    volumes:
      - logs:/var/log
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - elasticsearch
    ports:
      - "2020:2020"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

volumes:
  logs:
