# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Python script to the working directory
COPY app2.py .

# Run the Python script
CMD ["python", "app2.py"]
