version: '3.8'

services:
  component2:
    build:
      context: ./C2
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - project_network

  component3:
    build:
      context: ./C3
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./C3/output:/app/output
      - ./C3/logs:/app/logs
    networks:
      - project_network

  component1:
    build: ./C1
    ports:
      - "5000:5000"
    volumes:
      - ./C1/logs:/app/logs
    networks:
      - project_network
    depends_on:
      - component2

networks:
  project_network:
    driver: bridge
