version: '3.8'

services:
  component2:
    build: ./C2
    ports:
      - "5001:5001"
    volumes:
      - ./C2/logs:/app/logs  # Maps logs to the host
    networks:
      - project_network

  component1:
    build: ./C1
    ports:
      - "5000:5000"
    volumes:
      - ./C1/logs:/app/logs
    networks:
      - project_network
    depends_on:
      - component2

networks:
  project_network:
    driver: bridge
