# Use Python base image
FROM python:3.8

LABEL Maintainer="pain"

# Create a new user and group
RUN groupadd -r myuser && useradd -r -g myuser -m myuser

# Set working directory in the container
WORKDIR /usr/app/src

# Change ownership of the working directory to the new user
RUN chown -R myuser:myuser /usr/app/src

# Change to the new user
USER myuser

# Copy and install requirements
COPY requirements.txt test.py gpt2_ex_python.py .

# Install necessary packages
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy your application code to the container
COPY . .

# Command to run your application
CMD ["python", "gpt2_ex_python.py"]
