# Use Python base image
FROM python:3.8

LABEL Maintainer="pain"

# Set working directory in the container
WORKDIR /usr/app/src

# Copy and install requirements
COPY requirements.txt test.py .

# Install necessary packages
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy your application code to the container
COPY . .

# Command to run your application
CMD ["python", "test.py"]
