version: '3.8'

services:
  service1:
    build: ./service1
    ports:
      - "8081:80"
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - monitor_network
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  service2:
    build: ./service2
    ports:
      - "8082:80"
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - monitor_network
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  service3:
    build: ./service3
    ports:
      - "8083:80"
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - monitor_network
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  service4:
    build: ./service4
    ports:
      - "8084:80"
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - monitor_network
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  monitor:
    build: ./monitor
    deploy:
      resources:
        limits:
          memory: 100M
    networks:
      - monitor_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      - "5000:5000"

networks:
  monitor_network:
    driver: bridge
