version: '3.8'
services:
  nginx:
    image: openresty/openresty:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/lua:/etc/nginx/lua
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-nginx
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "your_password"]
    ports:
      - "6378:6379"
    volumes:
      - redis-nginx-data:/data

volumes:
  redis-nginx-data:
