version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'

  master:
    build: .
    container_name: master
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
    command: ["gunicorn", "--workers=12", "--timeout=3600", "-b", "0.0.0.0:5000", "app:app"]
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1G'

  worker1:
    build: .
    container_name: worker1
    command: ["python", "worker.py", "1"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker2:
    build: .
    container_name: worker2
    command: ["python", "worker.py", "2"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker3:
    build: .
    container_name: worker3
    command: ["python", "worker.py", "3"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker4:
    build: .
    container_name: worker4
    command: ["python", "worker.py", "4"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker5:
    build: .
    container_name: worker5
    command: ["python", "worker.py", "5"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker6:
    build: .
    container_name: worker6
    command: ["python", "worker.py", "6"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker7:
    build: .
    container_name: worker7
    command: ["python", "worker.py", "7"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker8:
    build: .
    container_name: worker8
    command: ["python", "worker.py", "8"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker9:
    build: .
    container_name: worker9
    command: ["python", "worker.py", "9"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker10:
    build: .
    container_name: worker10
    command: ["python", "worker.py", "10"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker11:
    build: .
    container_name: worker11
    command: ["python", "worker.py", "11"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  worker12:
    build: .
    container_name: worker12
    command: ["python", "worker.py", "12"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

volumes:
  redis-data:
