version: '3.8'

services:
  postgres:
    build:
      context: ./pg
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rankings_board
    volumes:
      - rankings_board_postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2GiB
          cpus: '2.0'
      
  python_listener:
    build:
      context: ./python_listener
    container_name: python_listener_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rankings_board
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    deploy:
      resources:
        limits:
          memory: 1GiB
          cpus: '1.0'
    depends_on:
      - postgres

volumes:
  rankings_board_postgres_data:
    external: true
