version: '3.8'

services:
  db:
    build: .
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
