global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape the node-exporter service
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
