version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "32181:2181"  # Change host port to 32181
  
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/create-topics.sh:/usr/local/bin/create-topics.sh
    command: >
      bash -c "
        kafka-server-start.sh /opt/bitnami/kafka/config/server.properties &
        sleep 5;
        create-topics.sh;
        wait"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - kafka

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
