version: '3'
services:
  load_balancer:
    image: nginx:latest
    ports:
      - "5432:5432"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db1
      - db2
      - db3

  db1:
    image: postgres:latest
    environment:
      POSTGRES_DB: arjun
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db1_data:/var/lib/postgresql/data
    networks:
      - backend

  db2:
    image: postgres:latest
    environment:
      POSTGRES_DB: arjun
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db2_data:/var/lib/postgresql/data
    networks:
      - backend

  db3:
    image: postgres:latest
    environment:
      POSTGRES_DB: arjun
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db3_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db1_data:
  db2_data:
  db3_data:

networks:
  backend:
