version: '3'
services:
  load_balancer:
    image: nginx:latest
    ports:
      - "5432:5432"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db1
      - db2
      - db3
    networks:
      - backend

  db1:
    image: postgres:latest
    environment:
      POSTGRES_DB: arjun
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - backend

  db2:
    image: postgres:latest
    environment:
      POSTGRES_DB: arjun
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db2_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - backend

  db3:
    image: postgres:latest
    environment:
      POSTGRES_DB: arjun
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db3_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - backend

  logstash:
    image: logstash:7.10.1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - backend
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    networks:
      - backend
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - backend
    depends_on:
      - logstash

volumes:
  db1_data:
  db2_data:
  db3_data:

networks:
  backend:
