version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  superset:
    image: apache/superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_random_secret_key
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - postgres
    restart: always
    command: >
      bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init &&
        superset run -p 8088 --with-threads --reload --debugger
      "

volumes:
  superset_home:
