version: '3.8'

services:
  nlp_service:
    build: ./nlp_service

  task_automation:
    build: ./task_automation

  text_to_speech:
    build: ./text_to_speech

  orchestration:
    build: ./orchestration
    ports:
      - "8000:8000"  # Expose port to communicate with host scripts
    depends_on:
      - nlp_service
      - task_automation
      - text_to_speech
