FROM ubuntu:focal
LABEL maintainer="Ravi Kumar <ravi.ameer@gmail.com>"
# No env variables for now
# ENV 
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y python3 \
                        curl \
                        vim \
                        net-tools
