global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kafka:9999']

  - job_name: 'zookeeper'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['zookeeper-exporter:5556']
