version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rankings_board
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2GiB
          cpus: '2.0'

volumes:
  postgres_data:
    driver: local
