apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name         tail
        Path         /var/log/app*.log
        Parser       json
        Tag          app_log

    [OUTPUT]      
        Name         es
        Match        *
        Host         elasticsearch
        Port         9200
        Index        app-logs
        Type         _doc

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
