apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app1
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app1
  template:
    metadata:
      labels:
        app: python-app1
    spec:
      containers:
      - name: python-app1
        image: python-app1:latest
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          type: DirectoryOrCreate
