version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
