FROM python:3.9

WORKDIR /app

# Install ZBar library
RUN apt-get update && apt-get install -y libzbar0

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY main.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
