version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
    container_name: "flask_api"
    ports:
      - "5000:5000"
    depends_on:
      - redis

  subscriber:
    build:
      context: ./subscriber
    container_name: "redis_subscriber"
    depends_on:
      - redis

  user_subscriber:
    build:
      context: ./user_subscriber
    container_name: "redis_user_subscriber"
    depends_on:
      - redis
    stdin_open: true
    tty: true
