version: '3.7'

services:
  hazelcast-node1:
    image: hazelcast/hazelcast:4.1
    ports:
      - "5701:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=127.0.0.1:5701

  hazelcast-node2:
    image: hazelcast/hazelcast:4.1
    ports:
      - "5702:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=127.0.0.1:5702

  hazelcast-node3:
    image: hazelcast/hazelcast:4.1
    ports:
      - "5703:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=127.0.0.1:5703
