version: '3.8'

services:
  tambola-app:
    # build: .
    image: ravikumarpidintla/tambola_app:0.0.1
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  db:
  logs:
