# version: '3.8'

services:
  p1:
    build: ./p1
    # volumes:
      # - ./p1/input:/app/input
      # - ./p1/output:/app/output
    volumes:
      - "D:\\src_git\\LP\\LP\\projects\\video_subtitle_summary\\p1\\input:/app/input"
      - "D:\\src_git\\LP\\LP\\projects\\video_subtitle_summary\\p1\\output:/app/output"

  p2:
    build: ./p2
    volumes:
      - "D:\\src_git\\LP\\LP\\projects\\video_subtitle_summary\\p1\\output:/app/input"  # Reads audio files from p1's output
      - "D:\\src_git\\LP\\LP\\projects\\video_subtitle_summary\\p2\\output:/app/output"  # Stores .srt files in p2's output